### ISSUE TITLE
Missing "setup.py" when pip install forte-wrappers from git

### ISSUE THREAD

**Issue by KiaLAN** [asyml/ForteHealth#30]
I am trying the example in examples/mimic_iii/. When I follow the README and run this command:

```bash
pip install git+https://git@github.com/asyml/forte-wrappers#egg=forte-wrappers[elastic,spacy]
```

pip shows this error:

```bash
ERROR: File "setup.py" not found for legacy project forte-wrappers[elastic,spacy] from git+https://****@github.com/asyml/forte-wrappers#egg=forte-wrappers[elastic,spacy].
```

It seems that `setup.py` is missing in forte-wrapper repo.

However, installing from pypi works well. Maybe we need to replace the above command with this one:
```bash
pip install forte.spacy forte.elastic
```

**Comment by KiaLAN** [comment]
Python and pip versions:

Python 3.6.13 :: Anaconda, Inc.
pip 21.2.2

**Comment by Piyush13y** [comment]
Hi @KiaLAN, thank you for bringing this up. We have recently made changes to our Forte-wrappers repository and its packaging structure, which is the root cause of the issue that you mention. I will be pushing a change(new command) to resolve this. I shall update the status of this issue, as soon as that's done:)
